# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_OPTIONS: '--openssl-legacy-provider'

steps:
  - checkout: self
    fetchDepth: 1

  - task: NodeTool@0
    inputs:
      versionSpec: '20.19.4'
    displayName: 'Use Node.js 20.19.4'

  # Clean install to avoid mismatched deps
  - script: |
      rm -rf node_modules package-lock.json
      npm cache clean --force
      npm install next@14.2.5 --save-exact
      npm install
      npm dedupe
    displayName: 'Clean install dependencies'

  - script: |
      echo "Webpack versions in tree:"
      npm ls webpack || true
      echo "Tapable versions in tree:"
      npm ls tapable || true
    displayName: 'Check dependency versions'

  - script: rm -rf .next
    displayName: 'Clean Next.js cache'

  - script: npm run build
    displayName: 'Build project'

  # Package and publish the build output
  - task: CopyFiles@2
    inputs:
      SourceFolder: '.next'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/next-build'
    displayName: 'Copy Next.js build output'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/next-build'
      ArtifactName: 'next-build'
      publishLocation: 'Container'
    displayName: 'Publish build artifacts'
