# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_OPTIONS: '--openssl-legacy-provider'

steps:
  - checkout: self
    fetchDepth: 1

  - task: NodeTool@0
    inputs:
      versionSpec: '20.19.4'
    displayName: 'Use Node.js 20.19.4'

  - script: |
      echo "Cleaning old modules and cache..."
      rm -rf node_modules package-lock.json .next
      npm cache clean --force

      echo "Installing fixed versions of dependencies..."
      npm install next@14.2.5 webpack@5.89.0 tapable@2.2.1 --save-exact --legacy-peer-deps
      npm dedupe

      echo "Checking dependency versions..."
      npm ls webpack || true
      npm ls tapable || true
    displayName: 'Install dependencies'

  - script: |
      echo "Building project..."
      npm run build
    displayName: 'Build project'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '.next'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/next-build'
    displayName: 'Copy Next.js build output'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/next-build'
      ArtifactName: 'next-build'
      publishLocation: 'Container'
    displayName: 'Publish build artifacts'
