# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# 1️⃣ Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

# 2️⃣ Install dependencies (npm ci requires package-lock.json)
- script: |
    cd web
    npm ci
  displayName: 'Install dependencies'

# 3️⃣ Build Next.js project
- script: |
    cd web
    npm run build
  displayName: 'Build Next.js project'

# 4️⃣ Copy .next build output to artifact staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: 'web/.next'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/.next'
  displayName: 'Copy .next build output'

# 5️⃣ Publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'
